name: Kattis CI

defaults:
  run:
    shell: zsh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'

    - name: Run tests
      run: |
        for d in *(/) do
          cd $d
          python3 ../test.py
          cd ..
